# Generated by Django 4.2.3 on 2023-07-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_starting_bid_listing_start_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='/static/empty_listing.jpeg', max_length=64),
        ),
    ]
