# Generated by Django 4.2.3 on 2023-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='../static/auctions/empty_listing.jpeg', max_length=64),
        ),
    ]
