# Generated by Django 4.2.3 on 2023-07-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
