# Generated by Django 4.2.3 on 2023-07-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_user_watchlist_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='headline',
            field=models.CharField(default='header', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
