# Generated by Django 4.2.3 on 2023-07-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='cover',
        ),
    ]
