# Generated by Django 4.2.3 on 2023-08-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
    ]
