# Generated by Django 4.2.3 on 2023-08-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow_delete_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_post', to='network.post')),
            ],
            bases=('network.post',),
        ),
    ]
